const data = {
  "state": {
    "0": "Massachuetts",
    "1": "Florida",
    "2": "Indiana",
    "3": "Maryland",
    "4": "Michigan",
    "5": "Minnesota",
    "6": "North Carolina",
    "7": "New Jersey",
    "8": "New York",
    "9": "Ohio",
    "10": "Oklahoma",
    "11": "Pennsylvania",
    "12": "South Carolina",
    "13": "Tennessee",
    "14": "Texas",
    "15": "Virginia",
    "16": "Vermont"
  },
  "popular_category": {
    "0": "health",
    "1": "health",
    "2": "health",
    "3": "health",
    "4": "health",
    "5": "health",
    "6": "health",
    "7": "health",
    "8": "health",
    "9": "health",
    "10": "social",
    "11": "health",
    "12": "health",
    "13": "health",
    "14": "health",
    "15": "health",
    "16": "social"
  },
  "tweet": {
    "0": "many thanks great day debate new york fine photo",
    "1": "daniel purvis 8th floor paul ruggeri 8th vault draggy bump final",
    "2": "post pic 4 girl crush tag 10 peopletag kpop",
    "3": "control ammo dont control gun",
    "4": "mrd almost forgot fb credential id better go update profile lil leave usual",
    "5": "first last time really inlove bow wow let hold really thought feeling like talking",
    "6": "datpiff mixtape promo get 1500 view 500 play 50 downloads 10 comment 10 rating",
    "7": "ybganthony new way looking dmz finding way trendsetters",
    "8": "94th minute away winner replay groan",
    "9": "message year 10 11 gcse math revise trust dont fail im stuck shite",
    "10": "closet straight jail new plan punish coming russia",
    "11": "new flag flying landscaping look fantastic ygs looking beautiful",
    "12": "pretty speak truth",
    "13": "ugly barbie literally best thing ive heard week",
    "14": "getting result twitter marketing get weekly following auto tweet 50wk",
    "15": "larry ellison kick oracle openworld 2015 introduction new oracle cloud service easeofuse",
    "16": "rita os recall journey refugee becoming one uk biggest star"
  },
  "user": {
    "0": "CrisisGroup",
    "1": "caseymagnesium",
    "2": "yunacide",
    "3": "cityguyusa",
    "4": "wesleycleo",
    "5": "NatalieOK1",
    "6": "djsalutemag",
    "7": "FinanzCashFlow",
    "8": "LittleScoff",
    "9": "Lucyalex14",
    "10": "gayfriendschat",
    "11": "Y115YGS",
    "12": "JuJuBabyWorld",
    "13": "courts_fellows1",
    "14": "DoctorTweetz",
    "15": "cloudpsi",
    "16": "YahooCelebUK"
  },
  "Analytics": {
    "0": { "economic": 0, "social": 1, "culture": 0, "health": 7 },
    "1": { "economic": 1, "social": 1, "culture": 1, "health": 10 },
    "2": { "economic": 0, "social": 0, "culture": 0, "health": 6 },
    "3": { "economic": 1, "social": 0, "culture": 1, "health": 2 },
    "4": { "economic": 0, "social": 0, "culture": 0, "health": 1 },
    "5": { "economic": 0, "social": 0, "culture": 0, "health": 1 },
    "6": { "economic": 0, "social": 0, "culture": 0, "health": 7 },
    "7": { "economic": 0, "social": 0, "culture": 0, "health": 3 },
    "8": { "economic": 0, "social": 1, "culture": 0, "health": 6 },
    "9": { "economic": 0, "social": 0, "culture": 0, "health": 4 },
    "10": { "economic": 0, "social": 1, "culture": 0, "health": 0 },
    "11": { "economic": 0, "social": 0, "culture": 0, "health": 3 },
    "12": { "economic": 0, "social": 0, "culture": 0, "health": 1 },
    "13": { "economic": 0, "social": 0, "culture": 0, "health": 1 },
    "14": { "economic": 1, "social": 0, "culture": 1, "health": 7 },
    "15": { "economic": 0, "social": 1, "culture": 0, "health": 7 },
    "16": { "economic": 0, "social": 1, "culture": 0, "health": 0 }
  }
}


export default data;